# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kevin/programming/PMOD_ACL_example/PMOD_ACL_example.srcs/sources_1/ip/Div/Div.xci
# IP: The module: 'Div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kevin/programming/PMOD_ACL_example/PMOD_ACL_example.srcs/sources_1/ip/Div/Div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Div'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/kevin/programming/PMOD_ACL_example/PMOD_ACL_example.srcs/sources_1/ip/Div/Div.xci
# IP: The module: 'Div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kevin/programming/PMOD_ACL_example/PMOD_ACL_example.srcs/sources_1/ip/Div/Div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
