# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z010clg400-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/kevin/programming/accel/ACL_IP/ACL_IP.cache/wt [current_project]
set_property parent.project_path /home/kevin/programming/accel/ACL_IP/ACL_IP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /home/kevin/programming/accel [current_project]
read_vhdl -library xil_defaultlib {
  /home/kevin/programming/accel/ACL_IP/ACL_IP.srcs/sources_1/imports/PmodACL_Demo/SPImaster.vhd
  /home/kevin/programming/accel/ACL_IP/ACL_IP.srcs/sources_1/imports/PmodACL_Demo/SPIinterface.vhd
  /home/kevin/programming/accel/ACL_IP/ACL_IP.srcs/sources_1/imports/PmodACL_Demo/slaveSelect.vhd
  /home/kevin/programming/accel/ACL_IP/ACL_IP.srcs/sources_1/imports/PmodACL_Demo/SPIcomponents.vhd
  /home/kevin/programming/accel/ACL_IP/ACL_IP.srcs/sources_1/imports/PmodACL_Demo/selData.vhd
  /home/kevin/programming/accel/ACL_IP/ACL_IP.srcs/sources_1/imports/PmodACL_Demo/ClkDiv_5Hz.vhd
  /home/kevin/programming/accel/ACL_IP/ACL_IP.srcs/sources_1/imports/PmodACL_Demo/PmodACL_Demo.vhd
}
catch { write_hwdef -file PmodACL_Demo.hwdef }
synth_design -top PmodACL_Demo -part xc7z010clg400-1
write_checkpoint -noxdef PmodACL_Demo.dcp
catch { report_utilization -file PmodACL_Demo_utilization_synth.rpt -pb PmodACL_Demo_utilization_synth.pb }
